# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# new comment 
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: apeis-48

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0'
          
    - name: Restore NuGet packages
      run: dotnet restore APEAIS-4.8.sln

    - name: Build solution
      run: msbuild /p:Configuration=Release APEAIS-4.8.sln


    - name: Stop IIS
      run: |
        net stop W3SVC
    - name: Copy Build Code
      run: |
        xcopy /E /Y /I c:\Users\jodyford\actions-runner2\_work\APEIS-48\APEIS-48\* C:\inetpub\wwwroot\apeis2
     
    - name: Start IIS
      run: |
        net start W3SVC
